// Mock user data
export const currentUser = {
  id: '1',
  name: 'Isaac Yidana',
  studentId: '11051970',
  email: 'iyidana@campus.edu',
  phone: '+233244123456', 
avatar: '/images/avatar.png',
  role: 'Student',
  department: 'Computer Science',
  rating: 4.8,
};
// Mock items data
export const mockItems = [
  {
    id: '1',
    title: 'iPhone 14 Pro',
    description: 'Space Black iPhone 14 Pro with a clear case. Lost it somewhere near the library entrance or study area on the second floor.',
    category: 'Electronics',
    brand: 'Apple',
    color: 'Space Black',
    location: 'Library Building',
    lastSeen: 'Library - 2nd Floor',
    date: new Date('2025-01-15'),
    status: 'lost',
    image: '/images/iphone-14-pro.jpeg',
    reportedBy: currentUser,
    postedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: '2',
    title: 'Blue Backpack',
    description: 'Navy blue backpack found at the Student Center.',
    category: 'Bags',
    brand: 'Jansport',
    color: 'Navy Blue',
    location: 'Student Center',
    date: new Date('2025-01-24'),
    status: 'found',
    image: '/images/blue-backpack.jpeg',
    reportedBy: {
      id: '2',
      name: 'Sarah Johnson',
      studentId: '11051980',
      email: 'sjohnson@campus.edu',
      phone: '+233 24 567 8901',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
      rating: 4.9,
    },
    postedAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
  },
  {
    id: '3',
    title: 'Car Keys',
    description: 'Mercedes Benz key fob with keychain. Lost in Parking Lot C.',
    category: 'Keys',
    brand: 'Mercedes Benz',
    color: 'Black',
    location: 'Parking Lot C',
    date: new Date('2025-01-23'),
    status: 'lost',
    image: '/images/mercedes-key.jpeg',
    reportedBy: currentUser,
    postedAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
  {
    id: '4',
    title: 'Physics Textbook',
    description: 'University Physics textbook found in Lecture Hall 3. Has name written inside.',
    category: 'Books',
    brand: 'Pearson',
    color: 'Blue',
    location: 'Science Building',
    lastSeen: 'Lecture Hall 3',
    date: new Date('2025-01-22'),
    status: 'found',
    image: '/images/physics-textbook.jpeg',
    reportedBy: {
      id: '3',
      name: 'Isaac Yidana',
      studentId: '11051970',
      email: 'iyidana@campus.edu',
      phone: '+233 20 234 5678',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
      rating: 4.7,
    },
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: '5',
    title: 'Laptop Charger',
    description: 'MacBook Pro charger found in Computer Lab.',
    category: 'Electronics',
    brand: 'Apple',
    color: 'White',
    location: 'Computer Lab',
    date: new Date('2025-01-24'),
    status: 'lost',
    image: '/images/laptop-charger.jpeg',
    reportedBy: {
      id: '4',
      name: 'Emma Wilson',
      studentId: '11052000',
      email: 'ewilson@campus.edu',
      phone: '+233 27 345 6789',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
      rating: 5.0,
    },
    postedAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
  },
  {
    id: '6',
    title: 'Water Bottle',
    description: 'Blue Hydro Flask water bottle found in the Gym.',
    category: 'Personal Items',
    brand: 'Hydro Flask',
    color: 'Blue',
    location: 'Gym',
    date: new Date('2025-01-21'),
    status: 'lost',
    image: '/images/water-bottle.jpeg',
    reportedBy: {
      id: '5',
      name: 'James Brown',
      studentId: '11052010',
      email: 'jbrown@campus.edu',
      phone: '+233 26 456 7890',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
      rating: 4.6,
    },
    postedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
];

// Categories
export const categories = [
  { id: 'all', name: 'All Items', icon: 'Grid' },
  { id: 'electronics', name: 'Electronics', icon: 'Smartphone' },
  { id: 'clothing', name: 'Clothing', icon: 'Shirt' },
  { id: 'books', name: 'Books', icon: 'Book' },
  { id: 'bags', name: 'Bags', icon: 'Backpack' },
  { id: 'keys', name: 'Keys', icon: 'Key' },
];

// Locations
export const campusLocations = [
  'Library Building',
  'Student Center',
  'Science Building',
  'Computer Lab',
  'Cafeteria',
  'Gym',
  'Parking Lot A',
  'Parking Lot B',
  'Parking Lot C',
];